on:
  pull_request:
    types: [opened, synchronize]

name: Entry Point Test
jobs:
  entry_point_test:
    name: Entry Point Test - Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build source distribution
        run: make package
      - name: Install package
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install unpacked_sdist/
      - name: Test entry point
        run: make entry-point-test
